name: agendamento
description: App de agendamento para barbearias e consultórios médicos.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Banco de dados
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Câmera e galeria
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  
  # Calendário
  table_calendar: ^3.0.9
  
  # URL launcher para redes sociais
  url_launcher: ^6.2.1
  
  # Ícones
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"  # Cor de fundo
  adaptive_icon_foreground: "assets/icon/app_icon.png"
